name: in_house_promotion
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: ">=3.3.4 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  equatable: ^2.0.3
  flutter_bloc: ^8.1.6
  firebase_remote_config: ^5.0.4
  shared_preferences: ^2.0.18

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
